# action.yml
name: 'GitHub Action for Fatpub'
description: 'Convert Markua to old-fashioned publisher Markdown ready for Pandoc'
inputs:
  template:
    description: 'The name of the template with the styles used by the publisher'
    required: true
    #default: 'ptg_awph02'
  in:
    required: true
  out: 
     required: true
#  single-file:
#    description: 'If the input is a single file (as opposed to a file of files like `book.txt`)'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --template
    - ${{ inputs.template }}
    - --output
    - ${{ inputs.out }}
    - ${{ inputs.in }}
#    - ${{ inputs.single-file }}
